#!/usr/bin/env python3
"""Writes the scripted real-app example takes (drive.py scripts), one per patch, each played
twice: as saved, and with its space macro (reverb/echo) down ("reduced"). Scripted
performances: a script plays the virtual controller, not a person.

    python3 docs/sound-palette-batch/scripts/make_examples.py   # -> scripts/examples/*.txt
"""
import os

OUT = os.path.join(os.path.dirname(__file__), "examples")
os.makedirs(OUT, exist_ok=True)

# E minor voicings (MIDI notes).
EM = [52, 59, 64, 67]
CMAJ7 = [48, 55, 59, 64]
D6 = [50, 57, 62, 66]
BM7 = [47, 54, 57, 62]


class S:
    def __init__(self):
        self.lines = ["sleep 3"]

    def add(self, *ls):
        self.lines += ls

    def sleep(self, s):
        self.lines.append(f"sleep {s:.2f}")

    def chord(self, notes, hold, vel=90, gap=0.0):
        for n in notes:
            self.add(f"midi on {n} {vel}")
        self.sleep(hold)
        for n in notes:
            self.add(f"midi off {n}")
        if gap:
            self.sleep(gap)

    def legato(self, notes, step, vel=100, overlap=0.12):
        """Each note starts `overlap` s before the previous ends (glide in LEGATO)."""
        prev = None
        for n, beats in notes:
            self.add(f"midi on {n} {vel}")
            if prev is not None:
                self.sleep(overlap)
                self.add(f"midi off {prev}")
                self.sleep(max(beats * step - overlap, 0.05))
            else:
                self.sleep(beats * step)
            prev = n
        self.add(f"midi off {prev}")

    def cc(self, num, v):
        self.add(f"midi cc 1 {num} {v}")

    def ramp(self, num, a, b, secs):
        self.add(f"midi ramp 1 {num} {a} {b} {secs}")

    def rec(self, on):
        self.add("click rec-start" if on else "click rec-stop")

    def write(self, name):
        with open(os.path.join(OUT, name + ".txt"), "w") as f:
            f.write(f"# Scripted example take: {name}. Generated by make_examples.py.\n")
            f.write("\n".join(self.lines) + "\n")


def cc_of(v):
    return round(v * 127)


def take(name, body, space_cc=None, space_value=None, pickups=()):
    """The saved sound, then (if `space_cc`) the same phrase with that macro at 0."""
    for variant in ["", "-reduced"] if space_cc else [""]:
        s = S()
        # Pick every mapped macro up at its saved value first (soft takeover).
        for num, v in pickups:
            s.cc(num, cc_of(v))
        if variant:
            s.cc(space_cc, cc_of(space_value))
            s.ramp(space_cc, cc_of(space_value), 0, 0.5)
            s.sleep(1.0)
        s.rec(True)
        s.sleep(0.5)
        body(s)
        s.rec(False)
        s.sleep(1.5)
        s.write(name + variant)


def strings(s):
    for c in [EM, CMAJ7, D6, BM7]:
        s.chord(c, 3.6, gap=0.4)
    # Ensemble up over a held chord, then a top line over the pad of the chord.
    for n in EM:
        s.add(f"midi on {n} 85")
    s.ramp(21, cc_of(0.5), 127, 3.0)
    s.sleep(3.5)
    s.ramp(21, 127, cc_of(0.5), 2.0)
    s.sleep(2.0)
    for n in EM:
        s.add(f"midi off {n}")
    s.sleep(0.2)
    s.legato([(71, 1), (72, 1), (74, 2), (76, 2), (74, 1), (71, 3)], 0.55, overlap=0.08)
    s.sleep(3.0)


def pad(s):
    s.ramp(21, cc_of(0.5), 110, 12.0)
    for c in [EM, CMAJ7, D6]:
        s.chord(c, 6.5, vel=80, gap=0.5)
    s.chord([40, 52, 59, 62, 66, 71], 7.0, vel=80)
    s.sleep(5.0)


def lead(s):
    # Legato phrase (glides between overlapping notes), then detached notes (no glide, new
    # attacks), then vibrato brought in on a held note.
    s.legato([(64, 2), (67, 1), (71, 3), (69, 1), (67, 1), (66, 2), (64, 4)], 0.42)
    s.sleep(0.8)
    for n in [71, 74, 76, 74]:
        s.add(f"midi on {n} 100")
        s.sleep(0.35)
        s.add(f"midi off {n}")
        s.sleep(0.2)
    s.sleep(0.4)
    s.add("midi on 76 105")
    s.ramp(21, cc_of(0.3), 115, 2.5)
    s.sleep(3.2)
    s.add("midi off 76")
    s.ramp(21, 115, cc_of(0.3), 0.5)
    s.sleep(0.6)
    s.legato([(79, 1), (78, 1), (76, 1), (74, 1), (71, 4)], 0.42, overlap=0.1)
    s.sleep(3.0)


def bass(s):
    s.sleep(8.0)
    s.ramp(20, cc_of(0.35), 100, 6.0)
    s.sleep(6.5)
    s.ramp(21, cc_of(0.4), 110, 4.0)
    s.sleep(4.5)
    s.ramp(20, 100, cc_of(0.35), 4.0)
    s.ramp(21, 110, cc_of(0.4), 4.0)
    s.sleep(6.0)


def breath(s):
    s.ramp(21, cc_of(0.5), 120, 10.0)
    for c in [[64, 71], [60, 67, 72], [62, 69, 74]]:
        s.chord(c, 5.0, vel=85, gap=0.8)
    s.legato([(76, 2), (79, 2), (78, 4)], 0.6, overlap=0.2)
    s.sleep(5.0)


def perc(s):
    s.sleep(8.0)
    s.ramp(20, cc_of(0.4), 110, 4.0)
    s.sleep(4.5)
    s.ramp(22, cc_of(0.4), 115, 4.0)
    s.sleep(4.5)
    s.ramp(20, 110, cc_of(0.4), 3.0)
    s.ramp(22, 115, cc_of(0.4), 3.0)
    s.sleep(5.0)


MACROS = {
    "strings": [0.4, 0.5, 0.3, 0.3],
    "pad": [0.4, 0.5, 0.3, 0.4],
    "lead": [0.5, 0.3, 0.3, 0.4],
    "bass": [0.35, 0.4, 0.4, 0.4],
    "breath": [0.5, 0.5, 0.4, 0.5],
    "perc": [0.4, 0.5, 0.4, 0.3],
}
for name, body in [("strings", strings), ("pad", pad), ("lead", lead), ("bass", bass),
                   ("breath", breath), ("perc", perc)]:
    m = MACROS[name]
    pick = [(20 + k, v) for k, v in enumerate(m)]
    # The space macro is m4 (Space / Echo / Room); the bass has none (it is dry): its
    # reduced take is skipped.
    space = None if name == "bass" else 23
    take(name, body, space, m[3], pick)
