#!/usr/bin/env python3
"""Writes the D06 demo performances twice: `NAME.events` (seconds + raw MIDI hex, for the
offline renderer `crates/engine/examples/render_midi.rs`) and `NAME.txt` (a drive.py script
that plays the same messages live through the virtual controller `midi_player`).

    python3 docs/midi-timing/scripts/make_demos.py docs/midi-timing/scripts

Demos: `lead` (patches/expressive/lead: held notes, bends, wheel vibrato, legato phrases),
`keys` (patches/expressive/split: pedalled chords, repeated notes, overlapping notes and
release tails on channel 1, a gliding bass with a wide bend dive on channel 2) and `timing`
(the same patch: off-grid 16th and 32nd ratchets against wheel sweeps).
"""
import math
import os
import sys


class Perf:
    def __init__(self):
        self.ev = []

    def raw(self, t, *b):
        self.ev.append((round(t, 6), " ".join(f"{x:02x}" for x in b)))

    def on(self, t, ch, note, vel=100):
        self.raw(t, 0x90 | (ch - 1), note, vel)

    def off(self, t, ch, note):
        self.raw(t, 0x80 | (ch - 1), note, 0)

    def note(self, t, dur, ch, note, vel=100):
        self.on(t, ch, note, vel)
        self.off(t + dur, ch, note)

    def cc(self, t, ch, num, val):
        self.raw(t, 0xB0 | (ch - 1), num, max(0, min(127, round(val))))

    def bend(self, t, ch, v):
        v = max(0, min(16383, round(v)))
        self.raw(t, 0xE0 | (ch - 1), v & 0x7F, v >> 7)

    def ramp(self, kind, t0, t1, ch, v0, v1, rate):
        n = max(1, round((t1 - t0) * rate))
        for k in range(n + 1):
            v = v0 + (v1 - v0) * k / n
            t = t0 + (t1 - t0) * k / n
            if kind == "bend":
                self.bend(t, ch, v)
            else:
                self.cc(t, ch, 1, v)

    def write(self, out, name, header):
        self.ev.sort(key=lambda e: e[0])
        with open(os.path.join(out, name + ".events"), "w") as f:
            f.write(f"# {header}\n# seconds, raw MIDI (generated by make_demos.py)\n")
            for t, b in self.ev:
                f.write(f"{t:.6f} {b}\n")
        with open(os.path.join(out, name + ".txt"), "w") as f:
            f.write(f"# {header}\n# Live through the virtual controller (scripted MIDI, not a"
                    " physical controller). Generated by make_demos.py.\n")
            for t, b in self.ev:
                f.write(f"wait {t + 3.0:.3f}\nmidi raw {b}\n")


C = 8192
UP2 = 16383  # full bend up (the patch's range)


def lead():
    p = Perf()
    # A held A4: vibrato comes in with the wheel and goes again.
    p.on(0.5, 1, 69, 96)
    p.ramp("wheel", 1.5, 3.5, 1, 0, 110, 50)
    p.ramp("wheel", 4.2, 5.0, 1, 110, 0, 50)
    p.off(5.2, 1, 69)
    # A legato phrase (overlapping notes glide in this patch).
    for i, (n, d) in enumerate([(69, 0.9), (72, 0.9), (74, 0.9), (72, 1.4)]):
        p.on(5.8 + i * 0.8, 1, n, 90)
        p.off(5.8 + i * 0.8 + d, 1, n)
    # A held E5, bent up a whole tone and back, then down and back.
    p.on(10.0, 1, 76, 100)
    p.ramp("bend", 10.8, 11.4, 1, C, UP2, 100)
    p.ramp("bend", 12.4, 12.8, 1, UP2, C, 100)
    p.ramp("bend", 13.4, 13.9, 1, C, 0, 100)
    p.ramp("bend", 14.5, 14.9, 1, 0, C, 100)
    p.off(15.6, 1, 76)
    # D5 with the wheel up while bending: vibrato on a bent note.
    p.on(16.2, 1, 74, 100)
    p.ramp("wheel", 16.6, 17.6, 1, 0, 127, 50)
    p.ramp("bend", 17.8, 18.5, 1, C, 12288, 100)
    p.ramp("bend", 19.6, 20.2, 1, 12288, C, 100)
    p.ramp("wheel", 20.2, 21.0, 1, 127, 0, 50)
    p.off(21.2, 1, 74)
    # Grace bends: each note starts a semitone low and bends up.
    for i, n in enumerate([72, 74, 76, 79]):
        t = 21.8 + i * 1.0
        p.bend(t - 0.01, 1, C - 4096)
        p.on(t, 1, n, 92)
        p.ramp("bend", t + 0.05, t + 0.25, 1, C - 4096, C, 100)
        p.off(t + 0.85, 1, n)
    # A long last note with vibrato fading out; the echo and reverb tail follow.
    p.on(26.0, 1, 69, 96)
    p.ramp("wheel", 26.5, 28.0, 1, 0, 100, 50)
    p.ramp("wheel", 28.5, 30.0, 1, 100, 0, 50)
    p.off(30.5, 1, 69)
    return p


def keys():
    p = Perf()
    ped = lambda t, down: p.cc(t, 1, 64, 127 if down else 0)
    # Pedalled chords: keys let go while the pedal holds them; re-pedal between chords.
    ped(0.4, True)
    for n in (60, 64, 67):
        p.note(0.5, 0.9, 1, n, 90)
    ped(2.3, False)
    ped(2.45, True)
    for n in (65, 69, 72):
        p.note(2.5, 0.8, 1, n, 85)
    ped(4.3, False)
    ped(4.45, True)
    for n in (62, 67, 71):
        p.note(4.5, 0.8, 1, n, 85)
    ped(6.4, False)
    # Repeated notes without the pedal: every one ends.
    for k in range(6):
        p.note(7.0 + k * 0.25, 0.18, 1, 72, 70 + 8 * k)
    # Repeated notes under the pedal: the same key restarts its own voice.
    ped(8.8, True)
    for k in range(4):
        p.note(9.0 + k * 0.3, 0.1, 1, 67, 90)
    ped(10.6, False)
    # Overlapping notes: each ends on its own release.
    for i, n in enumerate([60, 62, 64, 65, 67]):
        p.note(11.2 + i * 0.3, 1.1, 1, n, 80)
    # The bass on channel 2 joins: legato glides, then a one-octave bend dive.
    for i, (n, d) in enumerate([(36, 1.0), (43, 1.0), (41, 1.0), (36, 2.4)]):
        p.on(13.5 + i * 0.9, 2, n, 100)
        p.off(13.5 + i * 0.9 + d, 2, n)
    p.ramp("bend", 16.9, 17.8, 2, C, 0, 100)
    p.ramp("bend", 18.0, 18.4, 2, 0, C, 100)
    # Keys and bass together; the wheel opens only the keys' filter.
    for n in (57, 60, 64):
        p.note(19.0, 4.0, 1, n, 85)
    p.note(19.0, 4.0, 2, 33, 100)
    p.ramp("wheel", 19.5, 21.5, 1, 0, 127, 50)
    p.ramp("wheel", 21.5, 22.8, 1, 127, 0, 50)
    # A last pedalled chord; its release tail ends the piece.
    ped(23.8, True)
    for n in (55, 60, 64, 67):
        p.note(24.0, 0.6, 1, n, 80)
    p.note(24.0, 2.0, 2, 36, 90)
    ped(27.0, False)
    return p


def timing():
    p = Perf()
    beat = 60.0 / 132.0  # 132 bpm: a 16th is 5454.5 samples, never on the 64-sample grid
    s16 = beat / 4
    t0 = 0.5
    for bar in range(10):
        base = t0 + bar * 4 * beat
        for k in range(16):
            t = base + k * s16
            p.note(t, s16 * 0.45, 1, 72 if k % 4 == 0 else 67, 110 if k % 4 == 0 else 70)
            if k % 8 == 7:  # a 32nd ratchet into the next beat
                p.note(t + s16 / 2, s16 * 0.2, 1, 69, 60)
        for k in (0, 6, 10):
            p.note(base + k * s16, s16 * 1.6, 2, 36 if bar % 2 == 0 else 38, 100)
    # A triangle wheel sweep (block-rate modulation of the keys' filter).
    end = t0 + 10 * 4 * beat
    t = t0
    while t < end:
        v = 127 * (1 - abs(((t - t0) / 2.0) % 2 - 1))
        p.cc(t, 1, 1, v)
        t += 0.02
    p.cc(end, 1, 1, 0)
    return p


def pulse():
    """Measurement: 16ths at 132 bpm on channel 1 for 40 s, 60 % gate, one note at a time, so
    each onset is one gate edge in a recording of fixtures/gate-probe."""
    p = Perf()
    s16 = 60.0 / 132.0 / 4
    for k in range(int(40.0 / s16)):
        t = 1.0 + k * s16
        p.note(t, s16 * 0.6, 1, 60 + (k % 5), 100)
    return p


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(__file__)
    lead().write(out, "lead", "D06 demo: Expressive Lead (patches/expressive/lead)")
    keys().write(out, "keys", "D06 demo: pedal, repeats, overlaps, bass (patches/expressive/split)")
    timing().write(out, "timing", "D06 demo: off-grid ratchets and wheel sweeps "
                   "(patches/expressive/split)")
    pulse().write(out, "pulse", "D06 measurement: 16ths at 132 bpm, channel 1 "
                  "(docs/midi-timing/fixtures/gate-probe)")


main()
