[package]
name = "kabl-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "kabl-ui"
path = "src/main.rs"

[dependencies]
egui = "0.35"
eframe = { version = "0.35", default-features = false, features = [
    "glow",
    "default_fonts",
    "x11",
    "wayland",
] }
cpal = "0.18.2"
midir = "0.11.0"
rtrb = "0.4.0"
basedrop = "0.1.3"
hound = "3.5.1"
audio_thread_priority = "0.38"
image = { version = "0.25", default-features = false, features = ["png"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.1.6"
kabl-core = { path = "../core" }
kabl-engine = { path = "../engine" }
kabl-modules = { path = "../modules" }
kabl-standalone = { path = "../standalone" }

[dev-dependencies]
tempfile = "3.27.0"
