//! Built-in `Module` implementations (brief section 8's v1 table). All 9 named entries have a
//! `Module` impl now; two are intentionally partial — see their own doc comments:
//! - `osc.va`: saw waveform only, no hard sync.
//! - `lfo`: all 5 waveforms, no sync (brief itself defers "sync" — no clock exists yet, v3).

mod arp;
mod attenuverter;
mod chorus;
mod clock;
mod clock_div;
mod crossfade;
mod cues;
mod delay;
mod drive;
mod env_adsr;
mod filter_ladder;
mod filter_svf;
mod gain;
mod lfo;
mod logic;
mod macros;
mod midi_in;
mod mixer;
mod noise;
mod osc_fm;
mod osc_fm6;
mod osc_va;
mod osc_wt;
mod out;
mod quantizer;
mod random;
mod reverb;
mod ringmod;
mod sample_hold;
pub mod seq;
mod slew;
mod vca;

pub use chorus::{Chorus, CHORUS_INFO};
pub use clock::{Clock, Transport, CLOCK_INFO};
pub use clock_div::{ClockDiv, CLOCK_DIV_INFO};
pub use cues::{Cues, CUES, CUES_INFO};
pub use delay::{Delay, DelayLock, DELAY_INFO};
pub use drive::{drive_g, Drive, DRIVE_INFO};
pub use env_adsr::{EnvAdsr, ENV_ADSR_INFO};
pub use filter_ladder::{FilterLadder, FILTER_LADDER_INFO};
pub use filter_svf::{FilterSvf, FILTER_SVF_INFO};
pub use gain::{db_to_gain, Gain, GAIN_INFO};
pub use lfo::{Lfo, LfoSync, LFO_INFO, SYNC_LABELS, SYNC_TICKS};
pub use macros::{Macro, MACROS, MACRO_INFO};
pub use midi_in::{Change, KeySettings, MidiIn, MIDI_IN_INFO};
pub use mixer::{Mixer, LEGACY_LEVEL, MIXER_INFO};
pub use noise::{Noise, NOISE_INFO};
pub use osc_fm6::{OscFm6, ALGORITHMS, ALGORITHM_LABELS, FEEDBACK_RAD, MOD_RAD, OPS, OSC_FM6_INFO};
pub use osc_fm::{OscFm, FEEDBACK_MAX_RAD, OSC_FM_INFO, RATIO_LABELS};
pub use osc_va::{OscVa, OSC_VA_INFO};
pub use osc_wt::{OscWt, OSC_WT_INFO};
pub use out::{Out, OUT_INFO};
pub use reverb::{Reverb, REVERB_INFO};
pub use ringmod::{RingMod, RINGMOD_INFO};
pub use seq::{Direction, Seq, SEQ_INFO};
pub use vca::{Vca, VCA_INFO};
pub use arp::{Arp, ARP_INFO, MAX_NOTES};
pub use attenuverter::{Attenuverter, ATTENUVERTER_INFO};
pub use crossfade::{Crossfade, Pan, CROSSFADE_INFO, PAN_INFO};
pub use logic::{Comparator, Logic, COMPARATOR_INFO, LOGIC_INFO};
pub use quantizer::{snap, Quantizer, QUANTIZER_INFO, SCALE_LABELS};
pub use random::{Random, BIPOLAR_LABELS, RANDOM_INFO};
pub use sample_hold::{SampleHold, MODE_LABELS as HOLD_MODE_LABELS, SAMPLE_HOLD_INFO};
pub use slew::{Slew, MODE_LABELS as SLEW_MODE_LABELS, SLEW_INFO};
