#!/usr/bin/env python3
"""Writes performance.txt: the automated ~7-minute performance of patches/performance for
docs/rack-migration/drive.py. Every change goes through the app the way a player's would: CC
messages from a virtual MIDI controller (`midi` lines, the patch's CC 20-29 on channel 1),
MIDI notes for the lead, and real clicks on the Perform panel's transport and Record buttons.

    python3 docs/performance-batch/scripts/make_performance.py > docs/performance-batch/scripts/performance.txt

Timing is approximate: drive.py waits 0.3 s after every click, and the script's own sleeps add
up to the section starts in the comments.
"""

# CC numbers (channel 1) and the values that match the saved patch (soft takeover picks up there).
BASS, ARP, PAD, LEAD = 20, 21, 22, 23
BASS_CUT, ARP_CUT, PAD_CUT = 24, 25, 26
FEEDBACK, VERB_MIX, VERB_DECAY = 27, 28, 29
SAVED = {BASS: 28, ARP: 6, PAD: 14, LEAD: 32, BASS_CUT: 53, ARP_CUT: 79, PAD_CUT: 64,
         FEEDBACK: 60, VERB_MIX: 44, VERB_DECAY: 83}

out = []
t = 0.0


def line(s):
    out.append(s)


def sleep(s):
    global t
    line(f"sleep {s:.2f}")
    t += s + 0.3


def click(key):
    global t
    line(f"click {key}")
    t += 0.3


def ramp(cc, a, b, secs):
    line(f"midi ramp 1 {cc} {a} {b} {secs}")


def mark(text):
    line(f"# ~{int(t // 60)}:{int(t % 60):02d} {text}")


def phrase(notes, vel=96):
    """(midi note, beats) at 112 bpm; a note is released as the next starts."""
    beat = 60 / 112
    for n, beats in notes:
        line(f"midi on {n} {vel}")
        sleep(beats * beat - 0.3)
        line(f"midi off {n}")


line("# Generated by make_performance.py: the automated performance of patches/performance.")
line("sleep 2")
click("perform")
# Pick every mapping up where the patch has it, then set the opening: only the pad, and not yet.
for cc, v in SAVED.items():
    line(f"midi cc 1 {cc} {v}")
line("sleep 0.5")
ramp(BASS, 28, 0, 1)
ramp(ARP, 6, 0, 1)
ramp(PAD, 14, 0, 1)
ramp(PAD_CUT, 64, 45, 1)
ramp(VERB_MIX, 44, 60, 1)
ramp(VERB_DECAY, 83, 95, 1)
line("sleep 2")
click("rec-start")
t = 0.0
mark("atmosphere: the pad fades in and slowly opens")
ramp(PAD, 0, 16, 25)
ramp(PAD_CUT, 45, 62, 60)
sleep(55)
mark("first sequence: the bass fades in, dark, then opens")
ramp(BASS_CUT, 53, 40, 2)
sleep(2)
ramp(BASS, 0, 28, 12)
sleep(14)
ramp(BASS_CUT, 40, 66, 60)
sleep(36)
mark("second layer: the arp (7 steps against 8) joins; the reverb comes back a little")
ramp(ARP, 0, 8, 10)
ramp(VERB_MIX, 60, 44, 20)
sleep(25)
ramp(ARP_CUT, 79, 96, 15)
sleep(17)
ramp(ARP_CUT, 96, 72, 15)
sleep(15)
mark("lead")
ramp(FEEDBACK, 60, 74, 30)
E4, G4, A4, B4, D5, E5, Fs4 = 64, 67, 69, 71, 74, 76, 66
phrase([(B4, 4), (A4, 2), (G4, 2), (Fs4, 4), (E4, 4)])
phrase([(E4, 2), (G4, 2), (B4, 2), (D5, 2), (E5, 6), (D5, 2)])
ramp(FEEDBACK, 74, 60, 20)
phrase([(B4, 3), (A4, 1), (G4, 4), (A4, 2), (B4, 2), (E4, 8)])
phrase([(G4, 2), (A4, 2), (B4, 4), (D5, 4), (B4, 4), (A4, 4)], vel=88)
phrase([(E5, 3), (D5, 1), (B4, 4), (A4, 2), (G4, 2), (A4, 4), (B4, 8)])
sleep(3)
mark("breakdown: the sequences fade, the clock stops, tails ring")
ramp(BASS, 28, 0, 8)
ramp(ARP, 8, 0, 10)
ramp(VERB_DECAY, 95, 105, 10)
sleep(11)
click("prun:1")
phrase([(E5, 8), (D5, 8)], vel=80)
phrase([(B4, 12)], vel=76)
sleep(4)
mark("return: Restart, Run, both layers back")
click("prestart:1")
click("prun:1")
ramp(BASS, 0, 28, 2)
ramp(VERB_DECAY, 105, 90, 10)
sleep(4)
ramp(ARP, 0, 8, 4)
ramp(BASS_CUT, 66, 80, 30)
sleep(6)
phrase([(E4, 2), (G4, 2), (B4, 2), (D5, 2), (E5, 4), (D5, 2), (B4, 2)])
phrase([(A4, 4), (B4, 4), (G4, 4), (E4, 8)])
phrase([(B4, 2), (D5, 2), (E5, 4), (D5, 2), (B4, 2), (A4, 4), (G4, 4), (E4, 8)], vel=90)
ramp(BASS_CUT, 80, 55, 20)
sleep(20)
mark("outro: layers fade, the clock stops, the pad closes")
ramp(BASS, 28, 0, 15)
ramp(ARP, 8, 0, 18)
sleep(20)
click("prun:1")
ramp(PAD, 16, 0, 20)
ramp(PAD_CUT, 62, 40, 20)
sleep(26)
mark("stop recording")
click("rec-stop")
sleep(2)
line("shot end")
print("\n".join(out))
