#!/usr/bin/env python3
"""Writes soak.txt: a bounded ~30-minute session of patches/performance for drive.py, played
the way a person would: CC turns on several controls at once, lead notes and chords, rack knob
drags (live swaps, some overlapping), transport Stop/Run/Restart, Save and Load, a controller
unplug/replug, All notes off, and a new recording every cycle (so Stop → Record again, and
Load while recording, happen many times).

    python3 docs/performance-batch/scripts/make_soak.py > docs/performance-batch/scripts/soak.txt
"""

CYCLES = 10  # about 3 minutes each
out = ["# Generated by make_soak.py.", "sleep 2", "click perform"]
# Pick up every mapping where the patch has it.
for cc, v in {20: 28, 21: 6, 22: 14, 23: 32, 24: 53, 25: 79, 26: 64, 27: 60, 28: 44, 29: 83}.items():
    out.append(f"midi cc 1 {cc} {v}")


def phrase(notes, beat=0.54):
    for n, beats in notes:
        out.append(f"midi on {n} 100")
        out.append(f"sleep {beats * beat - 0.3:.2f}")
        out.append(f"midi off {n}")


for c in range(CYCLES):
    out.append(f"# cycle {c + 1}")
    out.append("click rec-start")
    # Several knobs at once, out and back.
    for cc, a, b in [(24, 53, 95), (25, 79, 100), (27, 60, 85), (28, 44, 70)]:
        out.append(f"midi ramp 1 {cc} {a} {b} 12")
    phrase([(64, 4), (67, 2), (71, 2), (74, 4), (71, 4)])
    out.append("dragby knob:6.resonance 0 -30")
    out.append("dragby knob:11.resonance 0 30")
    for cc, a, b in [(24, 95, 53), (25, 100, 79), (27, 85, 60), (28, 70, 44)]:
        out.append(f"midi ramp 1 {cc} {a} {b} 12")
    # A chord.
    for n in (64, 67, 71, 74):
        out.append(f"midi on {n} 90")
    out.append("sleep 3")
    for n in (64, 67, 71, 74):
        out.append(f"midi off {n}")
    # Fast back-and-forth drags: many swaps in a short time, some overlapping.
    for _ in range(3):
        out.append("dragby knob:1.bpm 0 -25")
        out.append("dragby knob:1.bpm 0 25")
    out.append("key ctrl+z")
    out.append("key ctrl+z")
    # Transport.
    out.append("click prun:1")
    out.append("sleep 6")
    out.append("click prestart:1")
    out.append("click prun:1")
    out.append("sleep 8")
    phrase([(76, 8), (74, 4), (71, 4), (69, 8)])
    if c % 3 == 1:
        # Save, then Load while recording (a fresh graph; the take goes on).
        out.append(f"save target/soak/saved-{c}")
        out.append("sleep 4")
        out.append("click load")
        out.append("sleep 6")
    if c == 4:
        # The controller unplugged with a note held, then back.
        out.append("midi on 76 110")
        out.append("sleep 1")
        out.append("midikill")
        out.append("sleep 4")
        out.append("midistart")
        out.append("sleep 4")
        for cc, v in {24: 53, 27: 60}.items():
            out.append(f"midi cc 1 {cc} {v}")
    if c == 7:
        out.append("midi on 64 100")
        out.append("midi on 67 100")
        out.append("sleep 1")
        out.append("click notes-off")
    out.append("sleep 130")
    out.append("click rec-stop")
    out.append("sleep 1")
out.append("shot soak-end")
print("\n".join(out))
