#!/usr/bin/env python3
"""Writes take.txt: the automated ~9-minute take of patches/composition for
docs/rack-migration/drive.py. Everything goes through the app the way a player's would: MIDI
from a virtual controller (`midi` lines: the macro knobs on CC 20-23, the lead level on CC 24,
cue buttons on CC 40-44, cancel 45, run/stop 46, all channel 1), MIDI notes for the lead, and
real clicks on the rack, drawer and Perform panel.

    python3 docs/composition-batch/scripts/make_take.py > docs/composition-batch/scripts/take.txt

Timing is approximate: drive.py waits 0.3 s after every click, and the script's own sleeps add
up to the section starts in the comments. A bar at 112 bpm is 2.14 s.
"""

ENERGY, MOTION, SPACE, GLOW, LEAD = 20, 21, 22, 23, 24
INTRO, MAIN, VARIATION, BREAKDOWN, RETURN, CANCEL, RUN = 40, 41, 42, 43, 44, 45, 46
# Saved values (0..1 × 127), so soft takeover picks each mapping up where the patch has it.
SAVED = {ENERGY: 51, MOTION: 64, SPACE: 38, GLOW: 38, LEAD: 32}

out = []
t = 0.0


def line(s):
    out.append(s)


def sleep(s):
    global t
    line(f"sleep {s:.2f}")
    t += s + 0.3


def click(key):
    global t
    line(f"click {key}")
    t += 0.3


def ramp(cc, a, b, secs):
    line(f"midi ramp 1 {cc} {a} {b} {secs}")


def button(cc):
    """A press and a release, as a hardware button sends them."""
    line(f"midi cc 1 {cc} 127")
    line(f"midi cc 1 {cc} 0")


def mark(text):
    line(f"# ~{int(t // 60)}:{int(t % 60):02d} {text}")


def phrase(notes, vel=96):
    """(midi note, beats) at 112 bpm; a note is released as the next starts."""
    beat = 60 / 112
    for n, beats in notes:
        line(f"midi on {n} {vel}")
        sleep(beats * beat - 0.3)
        line(f"midi off {n}")


E4, Fs4, G4, A4, B4, D5, E5 = 64, 66, 67, 69, 71, 74, 76

line("# Generated by make_take.py: the automated take of patches/composition.")
line("sleep 2")
click("perform")
for cc, v in SAVED.items():
    line(f"midi cc 1 {cc} {v}")
line("sleep 0.5")
# The opening: low energy, a wide space, the pad dim.
ramp(ENERGY, 51, 20, 1)
ramp(SPACE, 38, 62, 1)
ramp(GLOW, 38, 15, 1)
line("sleep 2")
click("rec-start")
t = 0.0

mark("Intro (startup banks: bass Intro, arp Bells); the pad glows in")
ramp(GLOW, 15, 75, 40)
sleep(30)
phrase([(B4, 6), (A4, 2), (G4, 8)], vel=70)
sleep(20)
phrase([(E5, 6), (D5, 2), (B4, 8)], vel=66)
sleep(12)

mark("edit an inactive bank while Intro plays: arp bank D (Drops), step 1 down")
click("perform")
click("module:7")
click("zoom:focus")
click("bank-edit:7.3")
line("dragby knob:7.d.p1 0 10")
sleep(2)
click("bank-edit:7.0")
click("perform")
sleep(2)

mark("Main: cue button; energy comes up, space comes in")
button(MAIN)
ramp(ENERGY, 20, 72, 16)
ramp(SPACE, 62, 36, 16)
sleep(18)
ramp(MOTION, 64, 100, 40)
phrase([(B4, 4), (A4, 2), (G4, 2), (Fs4, 4), (E4, 4)])
phrase([(E4, 2), (G4, 2), (B4, 2), (D5, 2), (E5, 6), (D5, 2)])
phrase([(B4, 3), (A4, 1), (G4, 4), (A4, 2), (B4, 2), (E4, 8)])
sleep(8)
phrase([(G4, 2), (A4, 2), (B4, 4), (D5, 4), (B4, 4), (A4, 4)], vel=88)
ramp(MOTION, 100, 80, 20)
sleep(24)
phrase([(E4, 2), (Fs4, 2), (G4, 4), (A4, 4), (B4, 8)], vel=90)
sleep(12)

mark("queue Variation, replace it with Breakdown inside the bar, then cancel: Main stays")
button(VARIATION)
line("sleep 0.2")
button(BREAKDOWN)
line("shot t1-replaced")
button(CANCEL)
line("shot t2-cancelled")
sleep(8)

mark("Variation: queued for real")
button(VARIATION)
line("shot t3-variation-queued")
sleep(10)
mark("arp direction to PEND on the Perform panel")
click("pslider:7.direction.2")
sleep(14)
mark("probability: arp bank C (playing) step 2 down on its knob")
click("perform")
click("bank-edit:7.2")
click("toggle:7")
sleep(1)
line("dragby knob:7.c.r2 0 50")
sleep(1)
click("toggle:7")
click("perform")
ramp(MOTION, 100, 70, 20)
phrase([(E5, 3), (D5, 1), (B4, 4), (A4, 2), (G4, 2), (A4, 4), (B4, 8)])
sleep(10)
click("pslider:7.direction.0")
mark("arp direction back to FWD")
sleep(14)
phrase([(B4, 2), (A4, 2), (G4, 2), (E4, 2), (G4, 8)], vel=84)
sleep(16)

mark("Breakdown: held bass, sparse drops, a big space")
button(BREAKDOWN)
ramp(ENERGY, 72, 15, 12)
ramp(SPACE, 36, 110, 20)
ramp(GLOW, 75, 100, 20)
sleep(22)
phrase([(E5, 8), (D5, 8)], vel=80)
phrase([(B4, 12)], vel=76)
sleep(20)
phrase([(G4, 8), (A4, 8), (E4, 16)], vel=70)
sleep(14)

mark("Return: Main's bass, Variation's arp")
button(RETURN)
ramp(SPACE, 110, 42, 14)
ramp(ENERGY, 15, 90, 20)
ramp(GLOW, 100, 60, 20)
sleep(16)
phrase([(E4, 2), (G4, 2), (B4, 2), (D5, 2), (E5, 4), (D5, 2), (B4, 2)])
phrase([(A4, 4), (B4, 4), (G4, 4), (E4, 8)])
ramp(MOTION, 70, 115, 20)
phrase([(B4, 2), (D5, 2), (E5, 4), (D5, 2), (B4, 2), (A4, 4), (G4, 4), (E4, 8)], vel=90)
sleep(24)
phrase([(E5, 3), (D5, 1), (B4, 4), (A4, 2), (G4, 2), (A4, 4), (B4, 8)])
ramp(MOTION, 115, 70, 20)
sleep(24)

mark("outro: back to Intro, energy down, then the clock stops and the tails ring")
button(INTRO)
ramp(ENERGY, 90, 20, 20)
ramp(SPACE, 42, 90, 20)
sleep(24)
button(RUN)
ramp(GLOW, 60, 10, 20)
sleep(24)
mark("stop recording")
click("rec-stop")
sleep(2)
line("shot end")
print("\n".join(out))
