[package]
name = "kabl-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rtrb = "0.4.0"
basedrop = "0.1.3"
wide = "1.7.1"

[dev-dependencies]
assert_no_alloc = "1.1.2"
hound = "3.5.1"
criterion = "0.8.2"

[[bench]]
name = "s2_potato"
harness = false

[[bench]]
name = "s3_simd_voices"
harness = false
