#!/usr/bin/env python3
"""Writes THIRD-PARTY-NOTICES.md: every crate the Linux build links (normal and build
dependencies of the workspace, no dev dependencies), its licence expression, and the licence
texts shipped inside each crate, deduplicated. Needs a populated cargo registry (run a build
first). Usage: python3 -I packaging/gen-notices.py > THIRD-PARTY-NOTICES.md"""
import collections, hashlib, json, pathlib, subprocess, sys

ROOT = pathlib.Path.cwd()
TARGET = "x86_64-unknown-linux-gnu"
meta = json.loads(subprocess.check_output(
    ["cargo", "metadata", "--format-version", "1", "--filter-platform", TARGET, "--locked"]))
pkgs = {p["id"]: p for p in meta["packages"]}
nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
members = set(meta["workspace_members"])

seen, stack = set(), list(members)
while stack:
    i = stack.pop()
    if i in seen:
        continue
    seen.add(i)
    for d in nodes[i]["deps"]:
        if any(k["kind"] != "dev" for k in d["dep_kinds"]):
            stack.append(d["pkg"])
third = sorted((pkgs[i] for i in seen - members), key=lambda p: (p["name"], p["version"]))

by_license = collections.defaultdict(list)
texts = collections.defaultdict(list)  # sha -> (text, [crates])
missing = []
for p in third:
    label = f'{p["name"]} {p["version"]}'
    by_license[p["license"] or "UNKNOWN"].append(label)
    crate = pathlib.Path(p["manifest_path"]).parent
    names = ("LICENSE", "LICENCE", "COPYING", "NOTICE", "UNLICENSE", "OFL", "UFL")
    dirs = [crate, crate / "fonts"]
    if p["source"] is None:  # vendored path crate: its licence sits at the vendor root
        dirs += [d for d in crate.parents if d != ROOT and ROOT in d.parents]
    files = [f for d in dirs if d.is_dir() for f in d.iterdir()
             if f.is_file() and f.name.upper().startswith(names)
             or f.is_file() and d.name == "fonts" and "license" in f.name.lower()]
    if not files:
        missing.append(label)
    for f in sorted(files):
        t = f.read_text(errors="replace").strip()
        h = hashlib.sha256(t.encode()).hexdigest()
        entry = texts.setdefault(h, [t, []])
        entry[1].append(label)

out = sys.stdout
out.write("# Third-party notices\n\n")
out.write("Generated by `packaging/gen-notices.py` from `Cargo.lock` for the Linux build "
          f"(`{TARGET}`, normal and build dependencies). {len(third)} crates, including the "
          "vendored `vendor/nice-plug` (ISC).\n\n")
out.write("## Licences by crate\n\n")
for lic in sorted(by_license):
    out.write(f"### {lic}\n\n")
    out.write(", ".join(by_license[lic]) + "\n\n")
if missing:
    out.write("Crates that ship no licence file (licence taken from their `Cargo.toml` only): "
              + ", ".join(missing) + "\n\n")
out.write("## Licence texts\n\nEach text appears once, followed by the crates that ship it.\n\n")
for t, crates in sorted(texts.values(), key=lambda v: v[1][0]):
    out.write("---\n\nShipped by: " + ", ".join(crates) + "\n\n```text\n" + t + "\n```\n\n")
